import type { TranscriptLine } from "@/lib/types";

/** Pre-loaded Q3 Launch planning meeting — July 14, 2026 */
export const DEMO_TRANSCRIPT: TranscriptLine[] = [
  {
    id: 101,
    speaker: "Ava Chen",
    role: "PM",
    timestamp: "00:01:12",
    text: "Thanks everyone. Goal today is lock the Q3 Launch scope and dates.",
  },
  {
    id: 102,
    speaker: "Marcus Webb",
    role: "Engineering Lead",
    timestamp: "00:02:05",
    text: "Backend is mostly green. Payment webhook retry is the only open item on our side.",
  },
  {
    id: 103,
    speaker: "Priya Nair",
    role: "Marketing",
    timestamp: "00:03:40",
    text: "Campaign creative needs a firm launch date by end of this week. Influencer hold expires August 20.",
  },
  {
    id: 104,
    speaker: "Ava Chen",
    role: "PM",
    timestamp: "00:05:18",
    text: "Understood. Let's confirm: public launch remains September 15 for Q3.",
  },
  {
    id: 105,
    speaker: "Jordan Hale",
    role: "Executive",
    timestamp: "00:06:02",
    text: "Board expects Q3. If we slip, I need two weeks' notice minimum.",
  },
  {
    id: 106,
    speaker: "Marcus Webb",
    role: "Engineering Lead",
    timestamp: "00:07:44",
    text: "September 15 is doable if we freeze API contracts by July 28. No major refactors after that.",
  },
  {
    id: 107,
    speaker: "Ava Chen",
    role: "PM",
    timestamp: "00:09:10",
    text: "Agreed. Marketing can book the September 15 window. Engineering freezes contracts July 28.",
  },
  {
    id: 108,
    speaker: "Priya Nair",
    role: "Marketing",
    timestamp: "00:10:01",
    text: "Great — I'll brief the agency that Q3 launch is locked for September 15.",
  },
  {
    id: 109,
    speaker: "Jordan Hale",
    role: "Executive",
    timestamp: "00:11:22",
    text: "Perfect. Treat September 15 as the committed date unless engineering flags a blocker.",
  },
  {
    id: 110,
    speaker: "Marcus Webb",
    role: "Engineering Lead",
    timestamp: "00:12:05",
    text: "Will do. Current risk is low; webhook work is two days max.",
  },
  {
    id: 111,
    speaker: "Ava Chen",
    role: "PM",
    timestamp: "00:13:30",
    text: "One more: onboarding funnel analytics must ship with launch. Same date.",
  },
  {
    id: 112,
    speaker: "Marcus Webb",
    role: "Engineering Lead",
    timestamp: "00:14:02",
    text: "Analytics rides on the existing events API. Fine as long as that API stays stable.",
  },
  {
    id: 113,
    speaker: "Priya Nair",
    role: "Marketing",
    timestamp: "00:14:32",
    text: "We'll draft the press kit assuming full feature set on September 15.",
  },
  {
    id: 114,
    speaker: "Ava Chen",
    role: "PM",
    timestamp: "00:15:40",
    text: "Decision recorded: Q3 Launch date is September 15. API freeze July 28. Marketing proceeds.",
  },
  {
    id: 115,
    speaker: "Jordan Hale",
    role: "Executive",
    timestamp: "00:16:12",
    text: "Thanks. Let's keep Discord updated if anything moves.",
  },
];
